print("                               ")
print("                               ")
print("*******************************")
print("*                             *")
print("Prueba de impresión en pantalla")
print("             PYTHON            ")
print("*                             *")
print("*******************************")
print("                               ")