lista_vacia=[]
lista_vacia.append(8)
print(lista_vacia)
lista_vacia.append(10.3)
print(lista_vacia)
lista_vacia.append("Hola")
print(lista_vacia)
lista_vacia.append(True)
print(lista_vacia)
lista_vacia[1]="Mundo"
print(lista_vacia)
lista_vacia[0]=lista_vacia[3]
print(lista_vacia)
